version: "3.2"
services:
  backend:
    restart: always
    container_name: backend
    image: tamunoseimiebi/devops-backend
    ports:
      - "9000:9000"
    networks:
      - hng-devops

  frontend:
    restart: always
    container_name: frontend
    image: tamunoseimiebi/devops-frontend
    ports:
      - "3000:3000"
    networks:
      - hng-devops

networks:
  hng-devops:
    driver: bridge
